### PR TITLE
feat: implement the trello plugin

### LINKED ISSUE #1881: Add a plugin for Trello
## Description
Collect data from Trello(Cloud).

## Pre-requisites
Please make sure you have access to [Trello API](https://developer.atlassian.com/cloud/trello/rest/api-group-actions/#api-actions-id-get). The API response will be stored in the raw data layer. before applying to this issue; otherwise, it's nearly impossible to finish this task.

## Describe the solution you'd like
Add a plugin for `trello`. Please refer to other data source plugins such as [jira](https://github.com/apache/incubator-devlake/tree/main/plugins/jira) and [tapd](https://github.com/apache/incubator-devlake/tree/main/plugins/tapd). 

This plugin performs 3 major tasks:
1. Collect data from [Trello API](https://developer.atlassian.com/cloud/trello/rest/api-group-actions/#api-actions-id-get). The API response will be stored in the raw data layer.
2. 1st ETL: transform the raw data and load it into the tool layer.
3. 2nd ETL: transform the tool layer data and load it into the domain layer. As Trello is an issue tracking tool, the final data to be loaded into the domain layer are mainly [entities from issue tracking domain](https://www.devlake.io/docs/DataModels/DevLakeDomainLayerSchema#domain-1---issue-tracking)

## How to start
Please follow the doc [how to add a plugin](https://devlake.apache.org/docs/DeveloperManuals/PluginImplementation).

## Additional notes
In DevLake, there're 3 layers of storage: 
- raw data layer: tables starting with `_raw_` 
- tool layer: tables starting with `_tool_`
- domain layer: tables with no prefix

You can set up DevLake and see the tables in MySQL.

### PR DESCRIPTION
**Pull request by jakezhu9**
### Summary
implement the trello plugin

### Does this close any open issues?
Closes #1881

### Screenshots
image

### Other Information
This plugin collects data from the Trello API and transforms the raw data into the tool layer. 
I didn't implement the task of converting the data to the domain layer because Trello is a flexible work management tool, and some fields cannot be converted to those in the issue with fixed rules, such as type and status.

### CODE REVIEW

**Comment by jakezhu9** [comment]
ok, I will fix them

**Comment by Startrekzky** [comment]
Hey @jakezhu9 , excellent work! We'll take a look at this PR. Are you in our community by the way?

**Comment by jakezhu9** [comment]
Hi @Startrekzky, I've joined Slack. Also, the CI errors has been fixed! I'm hoping this pr will help improve DevLake even further :)

**Comment by mappjzc** [comment]
> Hi @Startrekzky, I've joined Slack. Also, the CI errors have been fixed! I'm hoping this pr will help improve DevLake even further :)

Hi @jakezhu9 .I have tried to use your plugin but failed to test connection at first.
image
image
image

and I have checked the document of oauth.

It seems you don't use the full way for OAuth.

image
image
image

I can only get `Consumer Key` and `Consumer Secret`.

So I don't know how you config the connection to run it.

There are some codes from the document about how to use OAuth1.0 for Trello. 
https://glitch.com/edit/#!/trello-oauth?path=server.js%3A37%3A0
Maybe It can help you.

**Comment by jakezhu9** [comment]
Hi @mappjzc. You're absolutely right, I didn't fully implement oauth because it's a bit more complicated to set up.

Instead, I've been using a combination of an API key and token for authentication. You can find instructions for configuring this in the README and on the [Trello developer site](https://developer.atlassian.com/cloud/trello/guides/rest-api/api-introduction/).

One thing I should mention is that I haven't found a great way to store the API key and token in the plugin helper. Right now, I'm using helper.BasicAuth, which means you'll need to put the API key in the username field and the token in the password field. I know this isn't a good design and could cause some confusion. 

If you have any suggestions for how to improve this, please let me know and I'll work on making it better!

**Comment by klesh** [comment]
@jakezhu9 @mappjzc I see, I think it would be better to use the `AppKey` instead of the `BasicAuth`.
Note that we can modify the `req.Query` in the `SetupAuthentication` method as well to avoid confusion regarding which authorization method we opted for.
Keep in mind we should add a document to https://devlake.apache.org/ at the end of the development to explain the authorization etc.
Thanks for your hard work, appreciated it. 💪

**Comment by jakezhu9** [comment]
I have already switched to using the AppKey. I will add a document to explain the authorization process at the end of development. Thank you for your help and support, it is greatly appreciated.

**Comment by mappjzc** [comment]
> @jakezhu9 @mappjzc I see, I think it would be better to use the `AppKey` instead of the `BasicAuth`. Note that we can modify the `req.Query` in the `SetupAuthentication` method as well to avoid confusion regarding which authorization method we opted for. Keep in mind we should add a document to https://devlake.apache.org/ at the end of the development to explain the authorization etc. Thanks for your hard work, appreciated it. 💪

Thanks for your help.
I had already succeeded to test your connection. It works.

And I try to run a blueprint for it, But here have some problems.
image
As you see, It sends out the error that "boardId is required".

This error comes from PrepareTaskData as follows.
image
It decodes from the map option to TrelloOptions.

image
And in TrelloOptions, It required BoardId with json field "boardId"

But in the blueprint, there is only filed "scopeId" in the JSON string.
image

To see the makePipelinePlanV200 of your code, you use the filed "scopeId"  in the options JSON string.
image

Maybe you need to unify them in the way you like.

After I fixed this on my locally, this plugin can work successfully.

And another little thing. the CollectCheckItem and CollectChecklist Collect the same data.
It is enough only one.

**Comment by jakezhu9** [comment]
@mappjzc Thank you so much for reviewing my work carefully! I just realized that I made a mistake in the boardId and scopeId, but I'll get it fixed right away. I'm also working on adding `blueprint_test` to prevent similar issues from happening in the future.

As for CollectCheckItem and CollectChecklist, my original idea was to keep them separate since they are two different tasks. After giving it some thought, I agree with you that merging them into one task would be a better approach. I plan to keep only CheckItem and include the Checklist data within each item, as Checklist has only a few fields.

**Comment by jakezhu9** [comment]
Already fixed. There is an error about the commit message in ci, but it doesn't seem to be my reason, just ignore it.

**Review by mappjzc — APPROVED** [review]

**Comment by mappjzc** [comment]
> Already fixed. There is an error about the commit message in ci, but it doesn't seem to be my reason, just ignore it.
@jakezhu9 

Thank you so much.
It is a great pull request.

Can we have the privilege of obtaining more contact information about you for more convenient communication?
Like WeChat or others that you prefer to use?

**Comment by jakezhu9** [comment]
@mappjzc Absolutely! My WeChat ID is jakezhu9, and you can also reach me at [jakezhu9@gmail.com](mailto:jakezhu9@gmail.com)

**Pull request merged**
