### PR TITLE
fix: task data decode failed

### LINKED ISSUE #4315: [Bug][Customize] Cannot resolve RawDataTable and RawDataParams to TaskData
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Lack of mapstructure tag for `RawDataTable` and `RawDataParams` in `MappingRules` of customize.tasks, these two fields cannot be decoded when calling `mapstructure.Decode`

## Code snippets
https://github.com/apache/incubator-devlake/blob/25c68b456d0f89038b9ab70cb336156e70fff982/backend/plugins/customize/tasks/task_data.go#L20-L25
https://github.com/apache/incubator-devlake/blob/25c68b456d0f89038b9ab70cb336156e70fff982/backend/plugins/customize/impl/impl.go#L62

### What do you expect to happen

Nope

### How to reproduce

Nope

### Anything else

_No response_

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by narrowizard**
### Summary
Bug fix, for detail, to #4315 

### Does this close any open issues?
Closes #4315

### Screenshots
No

### CODE REVIEW

**Review by klesh — DISMISSED** [review]
LGTM

**Review by likyh — APPROVED** [review]

**Review by likyh — DISMISSED** [review]
It looks like this plugin can not run before this PR.

**Comment by narrowizard** [comment]
Please cherry-pick it to release-v0.15 after merge.

**Review by mindlesscloud — APPROVED** [review]
LGTM

**Comment by narrowizard** [comment]
Fix swagger docs  
image

**Pull request merged**
