### PR TITLE
[fix] typo enPoing

### LINKED ISSUE #1930: typo of jira from config-ui, maybe backend as well?
## Describe the bug
image

## Expected behavior
It shoud be `endpoint`

### PR DESCRIPTION
**Pull request by xgdyp**
# Summary

I searched all the projects including runtime files and I think there is only one typo left.

### Does this close any open issues?

Close #1930

### CODE REVIEW

**Comment by e2corporation** [comment]
This is a duplicate of #1950

**Comment by xgdyp** [comment]
oh, I find that. I don't see anyone talking on this issue so I do make this PR. Please close it , thanks ~

**Comment by e2corporation** [comment]
@xgdyp Not a problem, thanks for the contributing PR. I'll leave it open and wait for @klesh to pick one of them for merge.

**Comment by xgdyp** [comment]
@e2corporation  It's all ok. I close it.Thanks for your reply.

**Pull request closed without merging**
