### PR TITLE
feat: add teambition plugin

### LINKED ISSUE #1882: Add a plugin for Teambition
## Description
Collect data from Teambition(Cloud).

## Pre-requisites
Please make sure you have access to [Teambition API](https://open.teambition.com/help/folders/5da9273721dcbc001450670b) before applying to this issue; otherwise, it's nearly impossible to finish this task.

## Describe the solution you'd like
Add a plugin for `teambition`. Please refer to other data source plugins such as [jira](https://github.com/apache/incubator-devlake/tree/main/plugins/jira) and [tapd](https://github.com/apache/incubator-devlake/tree/main/plugins/tapd). 

This plugin performs 3 major tasks:
1. Collect data from [Teambition API](https://open.teambition.com/help/folders/5da9273721dcbc001450670b). The API response will be stored in the raw data layer.
2. 1st ETL: transform the raw data and load it into the tool layer.
3. 2nd ETL: transform the tool layer data and load it into the domain layer. As Teambition is an issue tracking tool, the final data to be loaded into the domain layer are mainly [entities from issue tracking domain](https://www.devlake.io/docs/DataModels/DevLakeDomainLayerSchema#domain-1---issue-tracking)

## How to start
Please follow the doc [how to add a plugin](https://devlake.apache.org/docs/DeveloperManuals/PluginImplementation).

## Additional notes
In DevLake, there're 3 layers of storage: 
- raw data layer: tables starting with `_raw_` 
- tool layer: tables starting with `_tool_`
- domain layer: tables with no prefix

You can set up DevLake and see the tables in MySQL.

### PR DESCRIPTION
**Pull request by coldgust**
### Summary
All tasks have been completed.

tasks:
- [x] connection and auth
- [x] account corresponding to teambition member
- [x] issue_labels corresponding to teambition tags(标签)
- [x] issue_comments corresponding to teambition task activity(任务动态)
- [x] issue_changelogs corresponding to teambition task activity(任务动态)
- [x] issue_worklogs corresponding to teambition task worktime(任务工时)
- [x] boards corresponding to teambition project(项目)
- [x] board_issues corresponding to teambition project_task
- [x] sprint_issues corresponding to teambition sprint_task
- [x] sprints corresponding to teambition sprints(迭代)
- [x] board_sprints corresponding to teambition project_sprints
- [x] issue_type corresponding to teambition scenario(任务类型)
- [x] issue_status corresponding to teambition taskflowstatus(工作流状态)
- [x] issue corresponding to teambition task(任务)
- [x] blueprint
- [x] e2e test

### Does this close any open issues?
Closes #1882

### Screenshots
Snipaste_2023-03-21_20-38-13
Snipaste_2023-03-21_20-38-34

### Other Information
After I finish the plugin development, I will also finish the config-ui development.

### CODE REVIEW

**Comment by coldgust** [comment]
Due to I am not familiar with the details of the project code, I think it will be of great help to me if someone is willing to communicate in Chinese via wechat. Thanks.

**Comment by likyh** [comment]
@coldgust Hi there, I have a few questions:

1. I noticed that OrganizationId is only used when collecting accounts. Can we retrieve it after the project collector has run? This would make it easier to support it in config-ui when there is only one ID option available.

2. Are you using it in blueprint advance mode?

3. It seems like all projects are being collected. Shouldn't we only collect what we need? This would make it easier to support teambition in config-ui.

Also, do you want to add support for some API in config-ui?

**Comment by likyh** [comment]
I have rebased this PR to the latest main. Please pull(rebase) in your local repo.

**Comment by coldgust** [comment]
Hi, @likyh 
1. All teambition api about getting account detail info are need OrganizationId. The project collector api only can get the userIds. But it has a trick to remove OrganizationId param. The TenantId(included in connection info) is equal to OrganizationId, cause teambition only support the organization tenant type. In summary, OrganizationId can get from connection.
2. Yes, I use advanced mode.
3. We can only get the project that correspond to the projectId params.
4. Yes, I am willing to add support for some API in config-ui in the future.

I will add a commit to impl 1 & 3 later.

**Review by likyh — DISMISSED** [review]

**Pull request merged**
