### PR TITLE
Refactor/refactor for dynamic connection

### PR DESCRIPTION
**Pull request by likyh**
### ⚠️ &nbsp;&nbsp;Pre Checklist

> Please complete _ALL_ items in this checklist, and remove before submitting

- [ ] I have read through the [Contributing](https://devlake.apache.org/community/) Documentation & [PR Template](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [ ] This PR is using a `label` (bug, feature etc.)
- [ ] My code is has necessary documentation (if appropriate)
- [ ] I have added any relevant tests
- [ ] This section (**⚠️ &nbsp;&nbsp;Pre Checklist**) will be removed when submitting PR

# Summary

This PR just refactor some code and fix some bugs.
1. delete ProviderIcons and ProviderFormPlaceholders and replace them with one config `ProviderConfigMap`. (`integrationsData` will refactor in future)
    1. delete all usages of ProviderIcons and ProviderFormPlaceholders
    2. use ProviderConfigMap.columns to control UI in `config-ui/src/pages/configure/connections/ConnectionForm.jsx`
    3. replace some hard code array with generated array by ProviderConfigMap such as `config-ui/src/components/Sidebar/MenuConfiguration.jsx`
2. replace some `switch(provider.id)`/`[xxx,yyy].includes(provider.id)`/`[jira,github]` with more common code.
3. replace specific vars in connection with an object.
4. move some local vars to the local scope from the global manager. Such as `connectionsList` in `config-ui/src/pages/blueprints/create-blueprint.jsx`
5. fix some bugs when reading code:
    1. proxy cannot save in Jenkins.
    2. adding a connection shouldn't allow users to go back to the form page
    3. connection saving must return after 2 seconds even though the network is in localhost.
    4. get connectionList in wrong way when request all plugin's connections
6. refactor some unused code:
    1. delete empty `useEffect`
    2. replace `maxConnectionsExceeded` with existing `connectionLimitReached` in `config-ui/src/pages/configure/integration/manage.jsx`
    3. ......

### Does this close any open issues?
Please mention the issues here.

### CODE REVIEW

**Comment by e2corporation** [comment]
@likyh @klesh I have a different plan for setting up dynamic plugins that I am drafting, I don't agree with much of the changes on this PR. Please invest time in feature tickets and stop refactoring UI.

**Comment by e2corporation** [comment]
@likyh @klesh Some of the intended goals on this ticket will be addressed and adapted for use with #2882

**Comment by likyh** [comment]
> @likyh @klesh I have a different plan for setting up dynamic plugins that I am drafting, I don't agree with much of the changes on this PR. Please invest time in feature tickets and stop refactoring UI.

Please support my idea. Or tell me why don't agree.

**Comment by e2corporation** [comment]
> > @likyh @klesh I have a different plan for setting up dynamic plugins that I am drafting, I don't agree with much of the changes on this PR. Please invest time in feature tickets and stop refactoring UI.
> 
> Please support my idea. Or tell me why don't agree. @e2corporation

@likyh As lead maintainer on UI I have more time invested in the frontend codebase, I have a certain idea of how the configuration system should evolve. Instead of the Product Owner creating a detailed ticket on the needs of "Dynamic" Plugins etc., you are taking it upon yourself without any discussion with me at all to refactor code that has hours of time in development and testing applied to it. This is not proper team co-ordination, and as you continue to run this nature of a refactor we have new features to add to this sprint and I need the UI system to be in a known state. All this time could have been invested in the other feature ticket I opened for Gitlab Proxy. It's not that I don't support your idea, but it has to be inline with my strategy. I already mentioned some of the goals you have on this PR will be accomplished on the other ticket and you will have the opportunity to continue development work there.

**Pull request closed without merging**
