### PR TITLE
feat: embeddable config-ui

### PR DESCRIPTION
**Pull request by mintsweet**
### ⚠️ Pre Checklist

> Please complete _ALL_ items in this checklist, and remove before submitting

- [ ] I have read through the [Contributing Documentation](https://devlake.apache.org/community/).
- [ ] I have added relevant tests.
- [ ] I have added relevant documentation.
- [ ] I will add labels to the PR, such as `pr-type/bug-fix`, `pr-type/feature-development`, etc.

# Summary

### Does this close any open issues?
Closes https://github.com/apache/incubator-devlake/issues/2241

### Screenshots
Include any relevant screenshots here.

### Other Information
Any other information that is important to this PR.

### CODE REVIEW

**Comment by mappjzc** [comment]
thanks for your pr.
@e2corporation can you help for review it?

**Comment by e2corporation** [comment]
> thanks for your pr.
> @e2corporation can you help for review it?

@mappjzc I'm not sure about this ticket Embeddable UI is not something we've discussed or approved in any recent meetings for this milestone. This looks like a foreign addition to this stack.

**Comment by e2corporation** [comment]
@mappjzc This seems like a separate UI project, why is it bundled with `incubator-devlake` project and not a new standalone project?

**Comment by mappjzc** [comment]
> @mappjzc This seems like a separate UI project, why is it bundled with `incubator-devlake` project and not a new standalone project?

@e2corporation  This is not my submitted pr. Maybe you would better to communicate with the creator of this pr ?

**Comment by klesh** [comment]
on hold, to be continued

**Comment by mintsweet** [comment]
This attempt will be suspended, and at the same time, because the code is much behind, it will turn off it.

**Pull request closed without merging**
