### PR TITLE
[fix-2829]: Compress tar-archived logs with gzip

### LINKED ISSUE #2829: [Bug][pipeline] Downloaded logging.tar.gz is not compressed
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

image

### What you expected to happen

command `file logging.tar.gz` should be seeing "gzip compressed data"

### How to reproduce

download `logging.tar.gz` from any pipeline.
run `file logging.tar.gz`
see error

### Anything else

_No response_

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by keon94**
closes #2829

### ⚠️ &nbsp;&nbsp;Pre Checklist

> Please complete _ALL_ items in this checklist, and remove before submitting

- [ ] I have read through the [Contributing](https://devlake.apache.org/community/) Documentation & [PR Template](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [ ] This PR is using a `label` (bug, feature etc.)
- [ ] My code is has necessary documentation (if appropriate)
- [ ] I have added any relevant tests
- [ ] This section (**⚠️ &nbsp;&nbsp;Pre Checklist**) will be removed when submitting PR

# Summary

### Does this close any open issues?
Closes #2829 

### Screenshots
image

### Other Information
Any other information that is important to this PR.

### CODE REVIEW

**Comment by keon94** [comment]
@klesh Due to a limitation on the viant/afs library, I had to go with Zip instead of gzip.
The output of running the file command will be: "Zip archive data, at least v2.0 to extract"

**Comment by klesh** [comment]
> @klesh Due to a limitation on the viant/afs library, I had to go with Zip instead of gzip. The output of running the file command will be: "Zip archive data, at least v2.0 to extract"

No problem

**Comment by klesh** [comment]
However, keep the following checklist in mind:
1. The extension part of the URL must be updated accordingly
2. The config-ui is to be updated as well @e2corporation 
3. Official document / swagger document should be updated if needed

**Comment by keon94** [comment]
On second thoughts, since plain tar is supported by this library it should be possible to just gzip that file using Go's native gzip library. I can look into that and see if it'll work.

**Comment by e2corporation** [comment]
@klesh @keon94 Are we changing filename + format on `v.13.0.0` release to ZIP filetype? If so I'll have to create another PR to update default logfile name on UI

**Comment by keon94** [comment]
@klesh My latest commit added support for gzip. Updated the testing screenshot above. FYI @e2corporation there'll be no need for UI changes

**Review by klesh — APPROVED** [review]
LGTM

**Pull request merged**
