### PR TITLE
feat: replace specific vars in connection with an object.

### LINKED ISSUE #2897: [Bug][config-ui] proxy in jenkins cannot be saved
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

image
image

### What you expected to happen

save proxy correctly.

### How to reproduce

Modify a Jenkins connection and open it again, and you'll see the proxy is empty and not saved.

### Anything else

_No response_

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by likyh**
# Summary

replace specific vars in connection with an object.

If we would add a new input on connection pages, we must pass it on several levels of components. That's not a good way to do it. So I use an object to replace it.

And I also fix #2897 in this PR.

### Does this close any open issues?
close #2897

### CODE REVIEW

**Comment by e2corporation** [comment]
@likyh This current Connection Form is a controlled form design of specific Connection Properties. You are destroying nicely designed state variables so you can stuff state in to a Configuration Object meant for reading the Plugin Config? This is not the way, I am going to decline this PR. There is nothing wrong with the state props and setters designed for managing the connection form. If there is a need to consolidate these props into one object at a later time I will do so.

**Comment by e2corporation** [comment]
@likyh Moreover, if you feel the need to create a separate form component which is built on dynamic inputs, you should make a separate component (`DynamicConnectionForm`) instead of erasing already working code and changing it's design strategy.

**Comment by likyh** [comment]
> @likyh This current Connection Form is a controlled form design of specific Connection Properties. You are destroying nicely designed state variables so you can stuff state in to a Configuration Object meant for reading the Plugin Config? This is not the way, I am going to decline this PR. There is nothing wrong with the state props and setters designed for managing the connection form. If there is a need to consolidate these props into one object at a later time I will do so.

So If we would add a new input on connection pages, we must find all of the usages and pass them on several levels of components. I don't think it a good way.

**Comment by likyh** [comment]
> @likyh Moreover, if you feel the need to create a separate form component which is built on dynamic inputs, you should make a separate component (`DynamicConnectionForm`) instead of erasing already working code and changing it's design strategy.

That's another PR.

**Comment by e2corporation** [comment]
> > @likyh This current Connection Form is a controlled form design of specific Connection Properties. You are destroying nicely designed state variables so you can stuff state in to a Configuration Object meant for reading the Plugin Config? This is not the way, I am going to decline this PR. There is nothing wrong with the state props and setters designed for managing the connection form. If there is a need to consolidate these props into one object at a later time I will do so.
> 
> So If we would add a new input on connection pages, we must find all of the usages and pass them on several levels of components. I don't think it a good way.

Even if we had to add 5 more state props to a connection form's signature, it's still manageable. You are worried about the wrong things.

**Review by e2corporation — COMMENTED** [review]
@likyh PR Declined. You have repeatedly proposed deleting controlled state setters because it's "easier" for you to manage. Having granular control over a form's controlled input props allows for more flexibility. If I find an immediate need to consolidate these properties into one structure I will do so, but not in the fashion you have proposed here.

**Pull request closed without merging**
