### PR TITLE
fix(m1): mysql image cannot be pulled

### PR DESCRIPTION
**Pull request by nicoabie**
### ⚠️ &nbsp;&nbsp;Pre Checklist

> Please complete _ALL_ items in this checklist, and remove before submitting

- [X] I have read through the [Contributing Documentation](https://devlake.apache.org/community/).
- [ ] I have added relevant tests.
- [ ] I have added relevant documentation.
- [ ] I will add labels to the PR, such as `pr-type/bug-fix`, `pr-type/feature-development`, etc.

# Summary

remove platform and move mysql version to latest

### Does this close any open issues?
Closes https://github.com/apache/incubator-devlake/issues/2945

### Screenshots
Include any relevant screenshots here.

### Other Information
Any other information that is important to this PR.

### CODE REVIEW

**Comment by abeizn** [comment]
@nicoabie Are you using a mac m1? or another version？
I don't think this parameter needs to be removed.

**Comment by warren830** [comment]
> @nicoabie I don't think this parameter needs to be removed if you are M1 arm64 chip. What is your docker-compose version?

I think I know this problem, for m1, we cannot pull mysql:8.0.26. We can only pull 8.0.30. We can change it to mysql：8

**Comment by warren830** [comment]
This also relates to #2642

**Comment by Startrekzky** [comment]
Hi @nicoabie , there is an error in the lint check of the commit message.
Try to re-push this commit again using the commit message 'fix: remove platform and move mysql version to latest'. Thanks

**Review by klesh — APPROVED** [review]
LGTM

**Pull request merged**
