### PR TITLE
fix: loadData columns type

### PR DESCRIPTION
**Pull request by long2ice**
# Summary

fix: loadData columns type

### Does this close any open issues?
Please mention the issues here.

### Screenshots
Include any relevant screenshots here.

### Other Information
Any other information that is important to this PR.

### CODE REVIEW

**Comment by klesh** [comment]
Hi, @long2ice, please provide more context of the PR, what is the problem of the code, and how this PR resolves the problem? Any screenshot to help others understand the problem and the solution?

**Comment by long2ice** [comment]
The `columns` receive value from database, before it's string type but in fact also include null, int, datetime  etc. So this PR fix it

**Review by klesh — APPROVED** [review]
OK, Please try to describe the context, and maybe post some screenshots to help reviewers understand the problem next time, thanks for your contribution.

**Comment by long2ice** [comment]
That's all right

**Pull request merged**
