### PR TITLE
feat: add `mode` to blueprint entity

### LINKED ISSUE #1987: add `mode` to `blueprint` as `enum` with possible values: `ADVANCED` / `NORMAL`,  mode can not be modified once set
## Description
According to new design, our existing plain `blueprint` is no enough. In order to satisfy both New User and Advanced User. We need `blueprint` to support different modes

## Describe the solution you'd like
add `mode` to `blueprint` as `enum` with possible values: `ADVANCED` / `NORMAL`,  mode can not be modified once set

### PR DESCRIPTION
**Pull request by klesh**
# Summary

Implement `mode` support for `blueprint`

1. added `mode` field to `blueprint`
2. `tasks` field is not required if `mode` == `NORMAL` because it would be generated by `settings` in the near future
3. added `isManual` to indicate if it is triggered by scheduler, `cronConfig` is required IFF `isManual == false`, but it gets validated if provided
4. `NORMAL` is not implemented yet

### Does this close any open issues?
Closes #1987 

### Screenshots
image
image
image

### CODE REVIEW

**Comment by klesh** [comment]
@e2corporation Please take a look the api input/output

**Comment by klesh** [comment]
@e2corporation Hi, I have talked to others, and here is the result:
1. `enable` means a blueprint is disabled or not, for `enable=false`, neither automation nor manual triggers are allowed.
2. as of `cronConfig` should be preserved in between Manual/Automated toggling, I agree, I will add another field `is_manual`
    - when `is_manual=true`, `cronConfig` is not required, however, it will be validated if provided.
    - when `is_manual=false`, `cronConfig` is required, and will be validated.
Let me know your thought.

**Comment by klesh** [comment]
PR updated

**Comment by klesh** [comment]
> > @e2corporation Hi, I have talked to others, and here is the result:
> > 
> > 1. `enable` means a blueprint is disabled or not, for `enable=false`, neither automation nor manual triggers are allowed.
> > 2. as of `cronConfig` should be preserved in between Manual/Automated toggling, I agree, I will add another field `is_manual`
> >    
> >    * when `is_manual=true`, `cronConfig` is not required, however, it will be validated if provided.
> >    * when `is_manual=false`, `cronConfig` is required, and will be validated.
> >      Let me know your thought.
> 
> I think in keeping with our camelCase conventions for API structs we should use `isManual` or just `manual`. `cronConfig` would always have a last known value or default to `hourly` for instance or whatever custom cron syntax the user defined.

They are, check the screen-shots.

**Comment by e2corporation** [comment]
@klesh the `isManual` changes are a nice addition, we'll have to continue the discussion later for `Blueprint.Mode` and how BE interprets 'NORMAL'. Frontend will always send a unified structure so BE can choose what subways to reference whether normal/advanced mode is used.

**Review by e2corporation — APPROVED** [review]
LGTM

**Pull request merged**
