### PR TITLE
[fix-2940][framework]: Add lazy caching of http codes for error handling and fix any broken Http error messages

### LINKED ISSUE #2940: [Bug][Core] Database Migration Required uses Wrong Status Code 500
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

As part of the assumptions for a required DevLake Database Migration, the Backend should return with a HTTP Status Code `428`, instead it using Internal Server `500`.

### What you expected to happen

API should always return with Status Code `428` If DB Migration is Required

### How to reproduce

N/A - UI will not show migration alert if api responds with internal server error 500

### Anything else

_No response_

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by keon94**
# Summary

1. Reworked the Type.Combine logic for combining multiple errors
2. Made some improvements to the Error interface as far as getting message information about that error, and returning an extended error JSON to the front-end with the structure:
```json
{
 "success": false,
 "message": "some string",
 "causes": ["cause1 string", "cause2 string", "cause3 string"]
}
```

3. All Http codes now supported, not just the statically provided Types (fixes #2940)
4. The work from (1) fixes the problem in #3031

### Does this close any open issues?
Closes #2940, #3031

### CODE REVIEW

**Comment by keon94** [comment]
@klesh this is ready for review. I tuned things in accordance with the proposal [here](https://github.com/apache/incubator-devlake/issues/3031#issuecomment-1242545195). cc @e2corporation

**Comment by keon94** [comment]
Sample plugin execution failure (error message display fixed)
image

**Comment by keon94** [comment]
Fix for #3031 screenshot:
image

**Comment by keon94** [comment]
> Fix for #3031 screenshot: image

error status is now 400 like before.

**Comment by klesh** [comment]
@keon94 Does it fix #2940? Could you provide screenshot for it?

**Comment by keon94** [comment]
@klesh Yes.
image

**Review by klesh — APPROVED** [review]

**Pull request merged**
