### PR TITLE
[fix_bug#2055][config] optimize configuration initialization function  and add endpoint debug log

### PR DESCRIPTION
**Pull request by SnowMoon-Dev**
# Summary

optimize configuration initialization function  and add endpoint debug log

close [#2055](https://github.com/apache/incubator-devlake/issues/2055)

## Verify this pull request

Manually verified the change by testing locally.

### CODE REVIEW

**Comment by warren830** [comment]
Nice job! Thanks man!

**Comment by SnowMoon-Dev** [comment]
> Nice job! Thanks man!

hello man, please help me reviewer

**Comment by SnowMoon-Dev** [comment]
There is contamination in this PR submission record, I submitted a new one

**Comment by thenicetgp** [comment]
@SnowMoon-Dev Hi, thank you for your contribution to Apache Devlake, Devlake community specially invites you to join our contributor group and issue you a contributor certificate. If you are willing, please contact 13120413800@163.com, looking forward to your reply.

**Pull request closed without merging**
