### PR TITLE
fix(config-ui): somethings for connections

### PR DESCRIPTION
**Pull request by mintsweet**
### Summary
1. fixed github token valid error.
2. remove old connection fields from plugin base.
3. integrate plugin config type.
4. add sort for plugin config.

### CODE REVIEW

**Comment by likyh** [comment]
which is valid in github token?

**Comment by mintsweet** [comment]
> which is valid in github token?

[fix(config-ui): github token valid error](https://github.com/apache/incubator-devlake/pull/4423/commits/81cdfe5efef1c7d85e75859b3506c11d50ac6eaf)

**Comment by likyh** [comment]
> > which is valid in github token?
> 
> [fix(config-ui): github token valid error](https://github.com/apache/incubator-devlake/pull/4423/commits/81cdfe5efef1c7d85e75859b3506c11d50ac6eaf)

Github test has never succeeded after prev refactor?

**Review by likyh — APPROVED** [review]

**Comment by mintsweet** [comment]
> > > which is valid in github token?
> > 
> > 
> > [fix(config-ui): github token valid error](https://github.com/apache/incubator-devlake/pull/4423/commits/81cdfe5efef1c7d85e75859b3506c11d50ac6eaf)
> 
> Github test has never succeeded after prev refactor?

tests that only affect the input.

**Pull request merged**
