### PR TITLE
fix: steps total nums is wrong

### LINKED ISSUE #2368: [Bug][runner] steps total nums is wrong under certain circumstances
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

when I run gitlab plugin, I find the total steps is 21, but it has 22 subtasks.
image

### What you expected to happen

the total tasks num is equal to the finish step.

### How to reproduce

run gitlab plugin in main branch.
and when a plugin has same subtask. such as:
image

### Anything else

_No response_

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by abeizn**
# Summary
Change the counting method of steps

### Does this close any open issues?
fix #2368 

### Screenshots
image

### Other Information
Any other information that is important to this PR.

### CODE REVIEW

**Comment by klesh** [comment]
I think we need to fix the "Subtask being executed twice" rather than the "total number"

**Comment by abeizn** [comment]
> I think we need to fix the "Subtask being executed twice" rather than the "total number"

Tasks for multiple tool layer layers use the same convertor. Instead of performing a task multiple times.

**Comment by abeizn** [comment]
> I think we need to fix the "Subtask being executed twice" rather than the "total number"

@klesh  updated.

**Review by klesh — APPROVED** [review]
LGTM

**Pull request merged**
