### PR TITLE
fix: test teambition connection

### PR DESCRIPTION
**Pull request by coldgust**
### Summary
fix teambition set the wrong code when test connection

### Does this close any open issues?
Closes xx

### Screenshots
Include any relevant screenshots here.

### Other Information
Any other information that is important to this PR.

### CODE REVIEW

**Comment by klesh** [comment]
Hi, @coldgust , thank you for the fix.

Please describe why you think this is the right way, did you find it out on their document? if so, please attach a link to the document, thanks.
Please attach screenshots to show the new code is working correctly.

**Comment by klesh** [comment]
Hi, @coldgust . Thank you for the information, 👍
Seems like their API design is a little bit off.
However, there is no proof to show the `code` inside the response body is `Http Status Code`, we should hardcode our API status code to 400 unless it can be proven.

**Comment by coldgust** [comment]
@klesh , thanks for the reminder.
I think `errorMessage` is helpful for users too.

**Review by klesh — APPROVED** [review]
LGTM

**Comment by coldgust** [comment]
#5066 have solved this issues.

**Pull request closed without merging**
