### PR TITLE
fix:SELinux context not set crashes container

### LINKED ISSUE #5474: [Bug][docker-compose] devlake container keeps restarting
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I used the instructions to install with docker, I used podman-compose instead of docker-compose.
I am unable to access the config ui and when examining the containers, I noticed that devlake_devlake_1 keeps restarting. Upon trying to attach, I saw this message:

`Version:  v0.17.0-beta4@
time="2023-06-13 23:32:39" level=warning msg="Failed to create filestream for logs. Logs will not be piped to files.
        caused by: open /app/logs/devlake.log: permission denied
        Wraps: (2) open /app/logs/devlake.log
        Wraps: (3) permission denied
        Error types: (1) *hintdetail.withDetail (2) *fs.PathError (3) syscall.Errno"
Attempting to write configuration to .env file.
panic: open ./.env: permission denied
Wraps: (2) open ./.env
Wraps: (3) permission denied
Error types: (1) *hintdetail.withDetail (2) *fs.PathError (3) syscall.Errno

goroutine 1 [running]:
main.main()
        /app/server/main.go:36 +0x93
`

In addition, browsing to http://localhost:4000/ I see the following message in the devlake_config-ui_1 console:
`
10.89.0.1 - - [13/Jun/2023:23:36:25 +0000] "GET /assets/index-14ed113a.js HTTP/1.1" 200 1424102 "http://localhost:4000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" "-"
2023/06/13 23:36:25 [error] 8#8: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 10.89.0.1, server: localhost, request: "GET /api/version HTTP/1.1", upstream: "http://10.89.0.8:8080/version", host: "localhost:4000", referrer: "http://localhost:4000/"

`

### What do you expect to happen

I expect to see the config ui and possibly the devlake container remain running and stable

### How to reproduce

`podman-compose up -d`
Use: https://devlake.apache.org/docs/GettingStarted/DockerComposeSetup
with: https://github.com/apache/incubator-devlake/releases/tag/v0.17.0-beta4 

### Anything else

Also tried docker-compose with sudo
also tried podman-compose with sudo
I'm running on Fedora 37

Thanks :heart: 

### Version

v0.17.0-beta4 

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by EliadCohen**
Following documented instructions for installation, using docker-compose (podman-compose) may result in the devlake container constantly crashing due to permissions on the .env

Closes #5474

### ⚠️ Pre Checklist

> Please complete _ALL_ items in this checklist, and remove before submitting

- [x] I have read through the [Contributing Documentation](https://devlake.apache.org/community/).
- [ ] I have added relevant tests.
- [ ] I have added relevant documentation.
- [x] I will add labels to the PR, such as `pr-type/bug-fix`, `pr-type/feature-development`, etc.

### Summary
What does this PR do?
a modification to the docker-compose file to set the SELinux context on .env for
the devlake container

### Does this close any open issues?
Closes #5474

### Screenshots
None relevant

### Other Information
First PR on this project. I hope I targetted the right file. Would appreciate insights, feedback and thanks for taking time to review

### CODE REVIEW

**Comment by hezyin** [comment]
Hi @EliadCohen, thanks for the PR, we really appreciate it. However, we won't be able to merge this PR for two reasons: we're already in the process of getting rid of the `.env` file altogether and we don't officially support `podman-compose`. If the devlake container crashes under `docker-compose`, let us know and we'll look into it.

@klesh Feel free to correct me if I'm wrong.

**Comment by EliadCohen** [comment]
> Hi @EliadCohen, thanks for the PR, we really appreciate it. However, we won't be able to merge this PR for two reasons: we're already in the process of getting rid of the `.env` file altogether and we don't officially support `podman-compose`. If the devlake container crashes under `docker-compose`, let us know and we'll look into it.
> 
> @klesh Feel free to correct me if I'm wrong.

Yes, it does crash with docker-compose, see #5474
Good news about getting rid of the .env file though... maybe worth waiting on this

**Comment by klesh** [comment]
@EliadCohen Thanks for your contribution, adding a mount option for SELinuex seems legit to me according to the docker run document. I'm not familiar with SELinux, Would it affect users that are not using SELinux?

As @hezyin  said, we are getting rid of the `.env` file, so, I think we should do the following:
1. this PR should be merged into `release-v0.17` instead of the `main` branch and `devops/releases/lake-v0.17.0/docker-compose.yml` should be updated too
2. remove this mount from `docker-compose-dev.yml` on the `main` branch

**Comment by EliadCohen** [comment]
I'm on it, thanks!

**Pull request closed without merging**
