### PR TITLE
fix: Fix broken Python config in Dockerfile

### PR DESCRIPTION
**Pull request by keon94**
### Summary
Python build config was broken. This PR fixes it.

### Does this close any open issues?
n/a

### CODE REVIEW

**Comment by klesh** [comment]
Hi, @keon94 , can you post screenshots to show it is working as expected? thanks.

**Comment by keon94** [comment]
Hi @matrixji, Will changing debian:bullseye-slim to python:3.11.2-slim-bullseye as base image have an impact?

**Comment by matrixji** [comment]
> Hi @matrixji, Will changing debian:bullseye-slim to python:3.11.2-slim-bullseye as base image have an impact?

As I know python: 3.11.2-slim-bullseye == debian:bullseye-slim + python:3.11.2, so it's reasonable.

**Review by matrixji — APPROVED** [review]
lgtm

**Pull request merged**
