### PR TITLE
Added PR template link

### LINKED ISSUE #2071: Put `Link a pr to an issues` into PR template
## Documentation Scope
PR template

## Describe the Change
Put the link of https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue to `.github/pull_request_template.md`
So contributors can take a look at it when creating PR

### PR DESCRIPTION
**Pull request by PrajwalBorkar**
### ⚠️ &nbsp;&nbsp;Pre Checklist

> Please complete _ALL_ items in this checklist, and remove before submitting

- [x] I have read through the [Contributing](https://devlake.apache.org/community/) Documentation
- [ ] This PR is using a `label` (bug, feature etc.)
- [ ] My code is has necessary documentation (if appropriate)
- [ ] I have added any relevant tests
- [ ] This section (**⚠️ &nbsp;&nbsp;Pre Checklist**) will be removed when submitting PR

# Summary

### Does this close any open issues?
Please mention the issues here.
Closes #2071 
### Screenshots
Include any relevant screenshots here.

### Other Information
Any other information that is important to this PR.

### CODE REVIEW

**Review by klesh — APPROVED** [review]
LGTM

**Comment by klesh** [comment]
@warren830 FYI

**Comment by warren830** [comment]
Hi @PrajwalBorkar , thanks for your pr! We'd like to issue you a certificate to honor your contribution. Can you join us on slack: https://join.slack.com/t/devlake-io/shared_invite/zt-1ak8wk48x-gEezOjTK7DsoZN7jJ1HCBA

**Comment by PrajwalBorkar** [comment]
> Hi @PrajwalBorkar , thanks for your pr! We'd like to issue you a certificate to honor your contribution. Can you join us on slack: https://join.slack.com/t/devlake-io/shared_invite/zt-1ak8wk48x-gEezOjTK7DsoZN7jJ1HCBA

Yeah sure. Thanks for invite :)

**Pull request merged**
