### PR TITLE
Update useSettingsManager.jsx - (spelling fix)

### PR DESCRIPTION
**Pull request by jasendo**
```diff
- endPoing
+ endpoint
```
Closes Ticket ID #1930

### CODE REVIEW

**Comment by e2corporation** [comment]
Please update PR Description with note regarding what Ticket ID this closes (#1930)

**Comment by jasendo** [comment]
> Please update PR Description with note regarding what Ticket ID this closes (#1930)

Sorry about that - I'm kinda new here.

**Comment by e2corporation** [comment]
@jasendo No problem, there was no need to close this PR but it looks like another PR was opened replacing this one.

**Comment by jasendo** [comment]
Oh my bad -- I wasn't sure what that did - glad I could help!

**Review by klesh — APPROVED** [review]

**Comment by warren830** [comment]
> Oh my bad -- I wasn't sure what that did - glad I could help!

Hi jasendo, may I have your email address? We'd like invite you to join our slack on https://join.slack.com/t/devlake-io/shared_invite/zt-18uayb6ut-cHOjiYcBwERQ8VVPZ9cQQw

**Pull request merged**
