### PR TITLE
Removed two Quick Start Links from README

### PR DESCRIPTION
**Pull request by Pranshu-Raj**
-Deploy in Temporal Mode (no url found)
-Deploy in Developer Mode (no url found)

### ⚠️ &nbsp;&nbsp;Pre Checklist

> Please complete _ALL_ items in this checklist, and remove before submitting

- [x] I have read through the [Contributing](https://devlake.apache.org/community/) Documentation & [PR Template](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [x] This PR is using a `label` (bug, feature etc.)
- [x] My code is has necessary documentation (if appropriate)
- [x] I have added any relevant tests
- [x] This section (**⚠️ &nbsp;&nbsp;Pre Checklist**) will be removed when submitting PR

# Summary

### Does this close any open issues?
Please mention the issues here.

### Screenshots
Include any relevant screenshots here.

### Other Information
Any other information that is important to this PR.

### CODE REVIEW

**Comment by Pranshu-Raj** [comment]
These two hyperlinks from **Quick Start** were returning 404.

**Comment by warren830** [comment]
Hi @Pranshu-Raj , sorry for the inconvenience, I found that the docs are moved to other places, could you please update this pr to change the link of those two instead of deleting them?
TemporalSetup: https://devlake.apache.org/docs/UserManuals/TemporalSetup
DeveloperSetup: https://devlake.apache.org/docs/DeveloperManuals/DeveloperSetup

**Comment by Pranshu-Raj** [comment]
Yes i can thanxx for the quick response.

**Comment by warren830** [comment]
> Yes i can thanxx for the quick response.

Thank you for your contribution. Are you in our slack channel?

**Comment by Pranshu-Raj** [comment]
Yes, I am in DevLake slack channel

**Pull request closed without merging**
