### PR TITLE
feat: setup database migration alert dialog on ui

### PR DESCRIPTION
**Pull request by e2corporation**
### 📦  Config-UI / App / Database Migration Alert

- [x] **Feature** Add Database Migration Alert Dialog & UX Flow
- [x] Create Database Migrations Hook `useDatabaseMigrations.jsx`
- [x] **Refactor** Remove UI/Rendering obligations from `Request.js` XHR Utility
- [x] Allow User-controlled Migration Confirmation Request
- [x] Test Migration Routine
- [x] **Chore** Code Cleanups & Linting
### Description

This PR adds a formal Database Migration Alert Dialog to Configuration UI. If the API has detected a migration, all its resource responses will return a `428` Status response, in which case a special `localStorage` key will be set to indicate that a migration warning is in effect. The Alert is mounted at the Application level so that it renders no matter what Page Service is being accessed. At this point the user can choose to **Proceed** with the migration operation or **Cancel** and take no action (Abort).

If the user chooses to **Proceed to Database Migration**, a `[GET]` request will be pushed to the Migration API Endpoint, if successful, the user will be given the option to continue or they can manually reload the browser. The local storage warning will be _removed_, and no additional migration warnings will be displayed.

If the user chooses to **Cancel Migration** (Abort), the migration warning local storage key will be temporarily removed, however they will continue to receive a migration warning if they attempt to use Configuration UI until DevLake is manually downgraded.

In the event of a Migration Failure, the alert dialog will transition states and allow the user to "Retry" the migration (though it will likely fail again) and advised to check the server logs for details.

### Does this close any open issues?
#2788

### Screenshots
`NOTE: "Downgrade" has been replaced with "Cancel"`
Screen Shot 2022-08-26 at 6 08 25 PM
Screen Shot 2022-08-26 at 7 49 33 PM
Screen Shot 2022-08-26 at 7 49 00 PM

Screen Shot 2022-08-29 at 3 59 13 PM

### CODE REVIEW

**Comment by e2corporation** [comment]
Rebased

**Comment by e2corporation** [comment]
Rebased

**Comment by e2corporation** [comment]
@klesh I would like to get this merged to `main` soon so the feature can be tested early, thanks.

**Review by klesh — APPROVED** [review]
LGTM

**Pull request merged**
