### PR TITLE
`hotfix` `v0.12.0` config-ui: fix jira blanking on tab-switch + entity restrictions

### PR DESCRIPTION
**Pull request by e2corporation**
### Description
This PR applies another set QA Bugfixes Config-UI for the `v0.12.0` **Blueprints Release**. It fixes an issue with multi-connection blueprints where a **JIRA** Connection's Transformation Settings Panel became "_blank_" when switched over from an alternate connection configuration. **Data Entity Restrictions** have been setup so that Transformation sections are linked to the selected entity types (where applicable). A workflow validation rule has also been added to prevent users from Advancing from the first step if a **disconnected** connection is selected.

- [x] **JIRA** Transformation Settings _BLANK_ on Tab Switch (Multi-conn)
   - [x] #2580 
- [x] Data Entity Transformation Restrictions
   - [x] #2582 
- [x] **UX**: Update Integration Provider Icons Primary Color
- [x] **Workflow Validation** - Prevent NEXT action if an **Offline** connection exists.
- [x] Code Linting  & Cleanups

### Does this close any open issues?
#2580, #2582

### Screenshots
Screen Shot 2022-07-22 at 9 52 43 PM

Screen Shot 2022-07-22 at 10 03 16 PM
Screen Shot 2022-07-22 at 10 03 28 PM
Screen Shot 2022-07-22 at 10 03 36 PM
Screen Shot 2022-07-22 at 10 17 48 PM

### CODE REVIEW

**Comment by e2corporation** [comment]
@klesh In regards to Data Entity Types and Transformation Settings, what entity scope does the "Additional Settings" section fall under? Currently, for JIRA, additional settings is grouped with Issue Tracking. For GitHub, additional settings is grouped with Code Review.

Additionally, Cross Domain or Source Code Management has no associated transformation settings rules linked to those scopes.

**Comment by klesh** [comment]
@e2corporation I'm not sure why we need a separated "Additional Setting", those setting should be part of "Data Entity Setting" IMO.
@Startrekzky @yumengwang03  Would you mind take a look at the question?

**Review by klesh — APPROVED** [review]
Tested, LGTM

**Comment by yumengwang03** [comment]
> 

Additional settings should be grouped with Source Code Management and Issue Tracking, because it is for calculating difference for commits and issues.

I noticed the copywriting also needs some adjustments accordingly:
- If Source Code Management and Issue Tracking are both selected for data entities: "Enable calculation of commit and issue difference"
- Only Source Code Management is selected: "Enable calculation of commit difference"
- Only Issue Tracking is selected: "Enable calculation of issue difference"

If this is too much work for v0.12, we can change the text to "Enable calculation of commit and/or issue difference" for now.

**Pull request merged**
